- packages/typescript/src/getProgram.ts
fix: https://github.com/johnsoncodehk/volar/issues/2138
getProgramBuildInfo is set to program in createBuilderProgram
https://github.com/microsoft/TypeScript/blob/v4.9.4/src/compiler/builder.ts#L1147
but with proxy don't have setter function it won't work
> fix: typescript buildInfo

- lerna.json
since you're using Lerna-Lite, it would be better to use Lerna-Lite's JSON Schema instead of Lerna's Schema which is slightly different that Lerna. Also note that I'm the maintainer of Lerna-Lite ;)
> chore: should be using Lerna-Lite schema instead of Lerna schema

- packages/monaco/LICENSE
- packages/monaco/README.md
- packages/monaco/package.json
- packages/monaco/src/editor.ts
- packages/monaco/src/index.ts
- packages/monaco/src/languages.ts
- packages/monaco/src/utils/autoFetchTypes.ts
- packages/monaco/src/utils/markers.ts
- packages/monaco/src/utils/monaco2protocol.ts
- packages/monaco/src/utils/protocol2monaco.ts
- packages/monaco/src/utils/provider.ts
- packages/monaco/src/worker.ts
- packages/monaco/tsconfig.build.json
- packages/monaco/worker.d.ts
- packages/monaco/worker.js
- pnpm-lock.yaml
- tsconfig.build.json
Implements 3 APIs for integrating Monaco:
- `import(@volar/monaco/worker).createLanguageService()`
- `import(@volar/monaco).languages.registerProvides()`
- `import(@volar/monaco).editor.activateMarkers()`
For more detail please see readme and reference to https://github.com/Kingwl/monaco-volar.
Closes #2
> feat: Integrate Monaco

- packages/language-server/src/common/server.ts
This is the [recommended way](https://github.com/microsoft/vscode-languageserver-node/issues/713#issuecomment-754551117) to declare up-front that the server supports workspace folders and is interested in change notifications. Without this server capability set, the vscode-languageserver-node dependency tries to register for workspace change notifications dynamically with a 'client/registerCapability' request. If the client doesn't support dynamic capability registration and responds to that request with a MethodNotHandled JSONRPC error, the promise for the request is rejected which causes the server to exit.
Also see this similar change in pyright https://github.com/microsoft/pyright/pull/4666
> Declare workspaceFolders support in server capabilities

- packages/language-server/src/common/project.ts
- packages/language-server/src/types.ts
- packages/language-service/package.json
- packages/language-service/src/baseLanguageService.ts
- pnpm-lock.yaml
Update `typescrpt-auto-import-cache` which now handles creating language service with the proxied host for auto completes and project reference support.
relates to: https://github.com/volarjs/typescript-auto-import-cache/pull/1
> feat(language-service): support auto imports and project references

- package.json
- pnpm-lock.yaml
- same as https://github.com/vuejs/language-tools/pull/2597
- in the next Lerna-Lite v2.0.0, I made `version` and `publish` as optional commands since it was requested by some users. So Lerna-Lite is now entirely modular and the user will need to manually install the command(s) he want to use (plus the CLI)
> chore: Lerna-Lite 2.0 publish & version are becoming optional commands

- packages/language-server/src/common/features/languageFeatures.ts
- packages/language-server/src/common/server.ts
- packages/language-server/src/common/workspaces.ts
- packages/language-server/src/types.ts
- packages/language-service/src/languageFeatures/codeLens.ts
Remove some settings usage for better compatibility with future Monoserver. This does not mean losing control, we just will control it in the language client.
Removed IDE settings:
- `volar.diagnostics.delay`
- `volar.codeLens.references`
- `volar.updateImportsOnFileMove.enabled`
Removed server init options:
- `disableFileWatcher`
> refactor: remove a few settings

- packages/kit/src/createLinter.ts
- packages/language-service/src/baseLanguageService.ts
- packages/language-service/src/languageFeatures/validation.ts
- packages/language-service/src/types.ts
- packages/language-service/src/utils/featureWorkers.ts
Implement Provide / Inject API ([similar to Vue](https://vuejs.org/guide/components/provide-inject.html)) for sharing AST / LanguageService or other instances across Services.
This is also the basis for making the Rules API AST agnostic.
- volar-service-foo
```ts
import { Service } from '@volar/language-service';
export default (): Service => (context): ReturnType<Service> => {
return {
provide: {
'foo-ast': (document: TextDocument) => parseFooAst(document),
},
};
};
```
- volar-service-bar
```ts
import { Service } from '@volar/language-service';
export default (): Service => (context): ReturnType<Service> => {
return {
provideDocumentColors(document) {
const fooAst = context.inject('foo-ast', document);
// ...
},
};
};
```
- volar-service-foo
```ts
import { Service, InjectionKey, …
```
> feat: Project / Inject APIs

- packages/language-server/src/node/fileSystem.ts
- packages/language-server/src/node/index.ts
- packages/language-service/src/baseLanguageService.ts
- packages/language-service/src/languageFeatures/validation.ts
- packages/language-service/src/types.ts
- packages/language-service/src/utils/featureWorkers.ts
This is another solution to replace #37, the new design only needs to import type, so no runtime dependencies.
In addition, in order to avoid over-design, `inject()` now can only be used in Rules and not in Services.
- volar-service-foo
```ts
import type { Service } from '@volar/language-service';
export interface MyProvide {
'foo-ast': (doc: TextDocument) => FooAST;
}
export default (): Service => (context): ReturnType<Service> => {
return {
provide: {
'foo-ast': parseFooAst
} satisfies MyProvide,
};
function parseFooAst(document: TextDocument) {
// ...
}
};
```
- volar-rule-no-baz
```ts
import type { Rule } from '@volar/language-service';
import type { MyProvide } from 'volar-service-foo';
export default (): Rule<MyProvide> = {
return {
run(document, ctx) {
const fooAst = …
```
> refactor: type-only Provide / Inject APIs

- packages/kit/src/createFormatter.ts
- packages/kit/src/createLinter.ts
- packages/kit/src/createProject.ts
- packages/language-core/src/types.ts
- packages/language-server/src/common/project.ts
- packages/language-server/tests/triple-directory/main.spec.ts
- packages/language-service/src/baseLanguageService.ts
- packages/language-service/src/types.ts
- packages/monaco/src/worker.ts
- packages/typescript/src/languageServiceHost.ts
In the past, we have been using TS getCurrentDirectory to return the root path of the current project, which is usually the upper level directory of tsconfig, which makes TS DocumentRegistry always unable to share SourceFile instances between multiple projects in monorepo, because the DocumentRegistry requires the currentDirectory to be the same.
Now `LanguageHost.getCurrentDirectory` has been removed, and `rootPath` and `workspacePath` have been added instead.
- `rootPath`: replaced the old `LanguageHost.getCurrentDirectory`
- `workspacePath`: use for `DocumentRegistry` and TS's `LanguageServiceHost.getCurrentDirectory`.
> Clearly distinguish between `rootPath` and `workspacePath`

- packages/kit/src/createLinter.ts
Very small PR, just adding a return to `logErrors` so that people can alter the text if needed. I also made the `console.log` optional, that way if someone wants to completely handle the printing themselves, they can
> feat(kit): Return text from logErrors so downstream consumers can manipulate it

- packages/typescript/src/languageServiceHost.ts
Related to https://github.com/vuejs/language-tools/discussions/2740
Profiling `.vue` file saves on a very big project:
Before (notice the 15s-long file save):
Profile:
[CPU-20231004T112107.zip](https://github.com/volarjs/volar.js/files/12802051/CPU-20231004T112107.zip)
After:
Profile:
[CPU-20231004T115709.zip](https://github.com/volarjs/volar.js/files/12802055/CPU-20231004T115709.zip)
> fix: performance issue with o(n^2) complexity of directoryExists()

- packages/monaco/src/utils/protocol2monaco.ts
Insert text containing `$` was incorrectly escaped as a snippet in older versions.
cc @remcohaszing, @Tahul
> fix(monaco): completion cannot insert text starting with `$`

- package.json
- packages/kit/package.json
- packages/labs/package.json
- packages/language-service/src/languageFeatures/callHierarchy.ts
- packages/monaco/src/editor.ts
- packages/typescript/package.json
- packages/typescript/src/languageServiceHost.ts
- packages/typescript/src/sys.ts
- packages/typescript/src/typescript/corePublic.ts
- packages/vscode/package.json
- pnpm-lock.yaml
For packages that are environment agnostic, import node modules should be avoided. If needed, polyfill packages are used directly, so no additional compatibility is required downstream.
- @volar/kit
- @volar/labs
- @volar/vscode
- @volar/cdn
- @volar/language-core
- @volar/language-server
- @volar/language-service
- @volar/monaco
- @volar/source-map
- @volar/typescript
There is an issue that needs further resolution, @volar/language-server/browser is importing typescript/lib/typescript.js directly, the code of typescript.js contains require("path"), so bundler still tries to resolve path module and requires downstream polyfill . But in fact, the path module is not used by typescript in the browser, because typescript checks whether the current environment is node. If not, the code that …
> fix: Avoid downstream need node polyfill for browser

- .npmrc
- packages/language-server/src/browser/index.ts
- packages/language-server/src/common/server.ts
- packages/language-server/src/node/index.ts
- packages/language-server/src/types.ts
- pnpm-lock.yaml
Fixed downstream must polyfill node modules for typescript. See #70
The language client should pass the typescript url via InitializationOptions.
> feat(language-server): Dynamically download TypeScript from CDN on Web

- packages/language-server/src/browser/index.ts
- packages/language-server/src/common/project.ts
- packages/language-server/src/protocol.ts
- packages/vscode/browser.d.ts
- packages/vscode/browser.js
- packages/vscode/node.d.ts
- packages/vscode/node.js
- packages/vscode/package.json
- packages/vscode/src/features/serverSys.ts
- packages/vscode/src/index.ts
- pnpm-lock.yaml
This PR only affects the browser language server.
- ~~Determine whether to send `fs.readDirectory`, `fs.readFile` requests based on `mtime` response by `fs.stat`, otherwise use the `workspaceState` cache~~ This reduces performance in real-world situations
- Loading files should show a progress bar
- language server no longer caches readDirectory
> fix(language-server, vscode): Properly handle FS requests on browser

- packages/kit/lib/createFormatter.ts
- packages/kit/lib/createLinter.ts
- packages/kit/lib/createProject.ts
- packages/language-core/lib/languageContext.ts
- packages/language-core/lib/types.ts
- packages/language-server/lib/common/features/customFeatures.ts
- packages/language-server/lib/common/features/languageFeatures.ts
- packages/language-server/lib/common/project.ts
- packages/language-server/lib/common/server.ts
- packages/language-server/lib/common/workspaces.ts
- packages/language-server/lib/types.ts
- packages/language-service/lib/baseLanguageService.ts
- packages/language-service/lib/documentFeatures/format.ts
- packages/language-service/lib/documents.ts
- packages/language-service/lib/languageFeatures/validation.ts
- packages/language-service/lib/types.ts
- packages/monaco/worker.ts
- packages/typescript/lib/getProgram.ts
- packages/typescript/lib/languageServiceHost.ts
The `LanguageHost`, `TypeScriptLanguageHost` interface was renamed to `ProjectHost`, `TypeScriptProjectHost` for more accurate meaning.
This is a pre-PR. The `TypeScriptProjectHost` interface and implementation will be abstract from the core to `@volar/typescript`. Downstream tools should be able to build project-aware language tooling (such as Deno) that has nothing to do with typescript, or non-project-aware language tooling (such as CSS). , JSON...).
> refactor: `LanguageHost` -> `ProjectHost`

- packages/monaco/index.ts
- packages/monaco/lib/editor.ts
- packages/monaco/lib/languages.ts
- packages/monaco/lib/utils/provider.ts
- packages/monaco/package.json
- packages/monaco/tsconfig.json
- packages/monaco/worker.ts
Since this code only works when bundled, there’s no need to compile it to CJS.
> Convert @volar/monaco to ESM

- packages/monaco/lib/editor.ts
- packages/monaco/lib/languages.ts
TypeScript namespaces are typically considered a bad practice, as they are TypeScript specific. Also they compile to something that can’t be tree-shaken, and the names used conflict with those of Monaco editor.
This is a breaking change.
> refactor(monaco): remove namespace usage

- packages/kit/lib/createChecker.ts
- packages/language-core/lib/createFileProvider.ts
- packages/language-core/lib/createTypeScriptProject.ts
- packages/language-server/lib/documentManager.ts
- packages/language-server/lib/project/simpleProject.ts
- packages/language-server/lib/project/typescriptProject.ts
- packages/language-server/lib/register/registerEditorFeatures.ts
- packages/monaco/worker.ts
- packages/typescript/lib/node/decorateLanguageServiceHost.ts
- packages/typescript/lib/protocol/createLanguageServiceHost.ts
`FileProvider` can no longer access all virtual files, as this requires implementing a synchronized function that updates all project source files. Instead, the upper layer should loop through its list of source files and request virtual files from the `FileProvider` one by one.
The advantage of this is that the synchronization function drops from O(n) to O(1).
> perf(language-core): only synchronize the source file currently needed

- packages/language-core/index.ts
- packages/language-core/lib/fileProvider.ts
- packages/language-core/lib/types.ts
- packages/language-core/lib/utils.ts
- packages/typescript/lib/protocol/createProject.ts
Add the `resolveSourceFileName` API, requiring the integrator to implement the conversion method from virtual file name to source file name.
This will solve the use case of typescript parsing external files and vue-tsc project reference.
cc @blake-newman
> feat(language-core): abstract virtual file name to source file name resolution

- packages/language-server/lib/register/registerLanguageFeatures.ts
- packages/language-service/lib/features/provideReferences.ts
- packages/language-service/lib/features/resolveCodeLens.ts
- packages/language-service/lib/types.ts
- packages/monaco/lib/provider.ts
`resolveReferencesCodeLensLocations` is used to exclude definitions for `referncesCodeLens` result. This logic can move to the services side after adding the `ReferenceContext` param.
> refactor(language-service): use `ReferenceContext` and replace `resolveReferencesCodeLensLocations`

- packages/typescript/index.ts
- packages/typescript/lib/node/proxyCreateProgram.ts
- packages/typescript/lib/node/transform.ts
- packages/typescript/lib/starters/createAsyncTSServerPlugin.ts
- packages/typescript/lib/starters/createTSServerPlugin.ts
- packages/typescript/lib/starters/runTsc.ts
- packages/typescript/package.json
- pnpm-lock.yaml
Abstract boilerplate code that needs to be implemented downstream into `@volar/typescript/lib/starters/*`.
- createTSServerPlugin: The language-independent part of `typescript-vue-plugin`
- createAsyncTSServerPlugin: The language-independent part of johnsoncodehk/mdx-analyzer/pull/2
- runTsc: The language-independent part of `vue-tsc`
> feat(typescript): add preset implementations

- packages/test-utils/index.ts
Not necessarily the *ultimate* fix, nonetheless this unblocks https://github.com/withastro/language-tools/pull/701
> feat(test-utils): add `openInMemoryDocument` method

- packages/kit/lib/createChecker.ts
- packages/language-core/lib/types.ts
- packages/language-server/lib/project/typescriptProject.ts
- packages/language-server/lib/server.ts
After `extraFileExtensions` is defined once by `LanguagePlugin`, the language server and kit checker no longer need to define it.
> refactor(language-core): `extraFileExtensions` option abstracte to `LanguagePlugin`

- packages/language-service/lib/types.ts
- packages/vscode/lib/features/documentDropEdits.ts
Added `createDataTransferFile` option to `DocumentDropEdit` to support creating file with contents provided by dataTransfer. This should resolve MDX drop edit's inability to create image file.
> feat(language-service): create `DataTransferFile` by `DocumentDropEdit`

- packages/language-server/lib/project/simpleProject.ts
- packages/language-server/lib/project/simpleProjectProvider.ts
- packages/language-server/lib/project/typescriptProject.ts
- packages/language-server/lib/project/typescriptProjectProvider.ts
- packages/language-server/lib/server.ts
- packages/language-server/lib/types.ts
After internal discussions, we believe that getProjectSetup and getServerCapabilitiesSetup can be simplified. Now, only implementing getServicePlugins and getLanguagePlugins is required.
This is an example after the astro update:
```ts
export function createServerOptions(
connection: Connection,
server: ReturnType<typeof createServer>
): ServerOptions {
return {
watchFileExtensions: [
'js',
'cjs',
'mjs',
'ts',
'cts',
'mts',
'jsx',
'tsx',
'json',
'astro',
'vue',
'svelte',
],
getServicePlugins() {
const ts = getTypeScriptModule();
const servicePlugins: ServicePlugin[] = [
createHtmlService(),
createCssService(),
createEmmetService(),
createTypeScriptService(ts),
createTypeScriptTwoSlashService(),
createTypescriptAddonsService(),
createAstroService(ts),
getPrettierService(),
];
return …
```
> refactor(language-server): no longer requiring project-specific service plugins

- packages/language-core/lib/types.ts
- packages/language-server/lib/register/registerEditorFeatures.ts
- packages/typescript/lib/node/decorateLanguageServiceHost.ts
- packages/typescript/lib/node/proxyCreateProgram.ts
- packages/typescript/lib/protocol/createProject.ts
Due to an upstream limitation, tsserver will throw when encountering a file name that does not exist in the file system, so Volar 2.0.0 no longer supports generating multiple virtual TS files from a single source file.
Since this breaks Astro's module syntax, generating multiple virtual TS files will now be supported again.
This only works for `@volar/language-server` and `@volar/kit`, but not for TS plugins executed in tsserver. This means that Astro is currently unable to migrate to the TS plugin.
- `LanguagePlugin.typescript` add a new `getExtraScripts()` API for returning extra scripts
- `LanguageContext.typescript` add a new `getExtraScript()` method
> feat(typescript): re-support extra virtual scripts for LSP and Kit

- packages/language-service/lib/features/provideCompletionItems.ts
- packages/language-service/lib/features/provideDocumentLinks.ts
- packages/language-service/lib/features/provideHover.ts
- packages/language-service/lib/features/resolveCompletionItem.ts
- packages/language-service/lib/features/resolveDocumentLink.ts
- packages/language-service/lib/utils/transform.ts
This resolves completion item descriptions the same way as hover descriptions are resolved.
The `transformDocumentLinkTarget` and `transformMarkdown` functions were both moved into `utils/transform`, but their implementation remains the same.
The fix was verified to work in MDX analyzer.
Refs https://github.com/mdx-js/mdx-analyzer/issues/394
> fix(language-service): transform markdown links in completion items

- packages/language-core/lib/fileRegistry.ts
- packages/language-core/lib/types.ts
- packages/language-server/lib/register/registerEditorFeatures.ts
- packages/language-service/lib/utils/featureWorkers.ts
In many cases `embeddedCodes` is always empty. It might as well be optional.
> refactor(language-core): make embeddedCodes optional in VirtualCode

- packages/language-server/lib/register/registerLanguageFeatures.ts
- packages/language-server/lib/server.ts
- packages/language-server/lib/types.ts
`@volar/language-server` introduced the `fullCompletionList` option in https://github.com/volarjs/volar.js/commit/fd0e24ca67f622aee2cad987221e21163e7aa963 to solve JSON parsing performance issues in certain IDEs.
Since version 2.0, these performance issues can be avoided by integrating with the TS plugin, making the workaround provided by `@volar/language-server` no longer necessary.
> refactor(language-server): remove `fullCompletionList` init option

- packages/language-service/lib/features/provideDiagnostics.ts
This fixes a caching issue regarding semanric diagnostics. I don’t fully understand why. Returning an empty array from https://github.com/mdx-js/mdx-analyzer/blob/f6a43853d5ae0509b93001fdf6f58e1466106605/packages/language-service/lib/service-plugin.js#L163 fixed the issue, so I figured this was an upstream problem in Volar.
Refs https://github.com/mdx-js/mdx-analyzer/issues/400
> fix(language-service): fix caching of semantic diagnostics

- packages/language-server/node.ts
- packages/vscode/lib/features/tsVersion.ts
Fix failed CI for https://github.com/microsoft/vscode/pull/171547.
> feat: webpack compatibility

- packages/language-server/lib/types.ts
- packages/test-utils/index.ts
This allows people to load TypeScript as suggested in #140. Since `initializationOptions` is of type `any` there, it doesn’t really matter. But the `InitializationOptions` interface is used by the test utils and prohibits the user from passing additional properties.
Also it’s nice if all Volar based language servers that do allow the client to pass the TypeScript SDK, do so in a consistent manner.
> fix(test-utils): allow unknown initialization options and expose `locale` option

- packages/language-service/lib/types.ts
This allows a service plugin instance provide value to be inferred without the need for an explicit type annotation on the `create` method.
> feat(language-service): add provide generic to ServicePlugin type

- packages/monaco/lib/ata.ts
- Should remove `/node_modules/` prefix from fileName, not uri
- Correct package name
> fix(monaco): correct package name resolve

- packages/typescript/lib/node/decorateProgram.ts
- packages/typescript/lib/node/proxyCreateProgram.ts
- packages/typescript/lib/node/transform.ts
- packages/typescript/lib/quickstart/runTsc.ts
- I'm trying to fix the issue I raised: 
https://github.com/vuejs/language-tools/issues/4194
- In the process of locating the problem, I found that when `tsc --incremental` is run repeatedly, the TS error message is converted by `tsc.js`'s `convertToDiagnosticRelatedInformation` method, which does not correctly get the text content corresponding to the error. So, I'm going to proxy this function to get `diagnostic.file.text` correctly.
- I don't think my solution is very elegant, and I'm worried about introducing new issues, but at least I hope to provide some clues. Since I'm not familiar with volar at the moment, I'm expecting a simpler fix as well.
> fix: vue-tsc does not show ts errors in the terminal with `--incremental`

- packages/typescript/lib/node/decorateProgram.ts
- packages/typescript/lib/node/transform.ts
- refs
https://github.com/vuejs/language-tools/issues/4099
https://github.com/vuejs/language-tools/issues/4194
- I've found that `program.getSourceFileByPath` is only used when enabled with the `incremental` option, and when **without** `incremental`, tsc diagnostics don't go through the `program.getSourceFileByPath`.
- So we still need the `transformSourceFile` function that was removed from the previous [**fix PR**](https://github.com/volarjs/volar.js/pull/158/files#diff-9b81391499358e6a051b86a6026a74f7dfdda8d53e856f7b11f696e703a93996L57). Sorry I didn't test this issue in time before.
> fix(typescript): transform source file for tsc without `incremental`

- packages/typescript/lib/node/decorateLanguageServiceHost.ts
- packages/typescript/lib/quickstart/createAsyncLanguageServicePlugin.ts
- packages/typescript/lib/quickstart/createLanguageServicePlugin.ts
As the architecture improves, `decorateLanguageServiceHost`'s modification of `getProjectVersion` seems to be no longer necessary, so it can be removed to reduce side effects.
> refactor(typescript): reduce `decorateLanguageServiceHost` side effects

- packages/kit/lib/createChecker.ts
- packages/kit/lib/createFormatter.ts
- packages/language-core/index.ts
- packages/language-core/lib/types.ts
- packages/language-server/lib/project/simpleProject.ts
- packages/language-server/lib/project/typescriptProject.ts
- packages/language-server/lib/server.ts
- packages/language-service/lib/features/provideDocumentFormattingEdits.ts
- packages/monaco/worker.ts
- packages/typescript/lib/common.ts
- packages/typescript/lib/node/proxyCreateProgram.ts
- packages/typescript/lib/protocol/createProject.ts
- packages/typescript/lib/quickstart/createAsyncLanguageServicePlugin.ts
- packages/typescript/lib/quickstart/createLanguageServicePlugin.ts
Endpoints is no longer required to provide `getLanguageId`, but require provided by the `LanguagePlugin`. Because `LanguagePlugin` has the complete context to calculate `languageId` of a file path. For Vue, it depends on `extensions`, `vitePressExtensions`, `petiteVueExtensions` options.
> refactor(language-core): resolved language ID by LangaugePlugin

- packages/eslint/LICENSE
- packages/eslint/index.ts
- packages/eslint/package.json
- packages/eslint/tsconfig.json
- pnpm-lock.yaml
- tsconfig.json
Added `@volar/eslint` package to export `createProcessor` method. `Processor` is the interface for ESLint to handle virtual code conversion. Downstream tools should build a complete ESLint plugin by themselves.
Here we take Vue as an example.
- eslint-plugin-vue.js
```js
const { createProcessor } = require('@volar/eslint');
const vue = require('@vue/language-core');
const ts = require('typescript');
module.exports.create = create;
function create(tsconfig) {
const commonLine = vue.createParsedCommandLine(ts, ts.sys, tsconfig);
const languagePlugin = vue.createVueLanguagePlugin(
ts,
filename => filename,
ts.sys.useCaseSensitiveFileNames,
() => '',
() => commonLine.fileNames,
commonLine.options,
commonLine.vueOptions,
);
return {
processors: {
vue: createProcessor([languagePlugin], …
```
> feat: add ESLint integration

- packages/language-server/lib/project/simpleProject.ts
When virtual code was created, the URI was passed as the language ID. Within MDX this means sometimes no virtual code was created at all, breaking semantic diagnostics and syntax toggles. The effects may be different for other implementations.
> fix(language-server): pass correct languageId when creating virtual code

- .github/workflows/auto-fix.yml
- .github/workflows/test.yml
- package.json
This makes corepack automatically pick the correct version of pnpm to use.
The pnpm GitHub action also supports this field.
> chore: specify packageManager in package.json

- packages/test-utils/index.ts
Using the IPC transport, breaks code coverage. This is related to https://github.com/bcoe/c8/issues/189.
> fix(test-utils): use stdio transport for test server

- extensions/labs/src/common/showVirtualFile.ts
- extensions/labs/src/views/serversView.ts
- extensions/labs/src/views/virtualFilesView.ts
- packages/language-core/lib/types.ts
- packages/language-server/lib/register/registerEditorFeatures.ts
- packages/language-server/lib/types.ts
- packages/language-server/protocol.ts
- packages/vscode/index.ts
Vue language tools used to be the only extension that integrated Codegen Stacks. Since the latest version of Vue language tools has removed the debug feature, this feature is no longer used by any framework, so we can remove it.
> refactor: remove "Codegen Stacks" debug feature

- packages/language-core/lib/types.ts
- packages/typescript/lib/resolveModuleName.ts
Add `resolveHiddenExtensions` option to `LanguagePlugin#typescript`. When enabled, `resolveModeName` will attempt to add extra extensions to resolve's module name.
> feat(language-core): add option to resolve hidden extensions

- packages/language-core/lib/types.ts
- packages/typescript/lib/node/decorateLanguageService.ts
- packages/typescript/lib/node/decorateLanguageServiceHost.ts
- packages/typescript/lib/node/proxyCreateProgram.ts
- packages/typescript/lib/node/transform.ts
Add option to disable the behavior mentioned at https://github.com/volarjs/volar.js/discussions/188#discussioncomment-9569561.
cc @piotrtomiak
> feat(typescript): add option to prevent offset in plugin mode and tsc

- packages/eslint/index.ts
- packages/language-core/index.ts
- packages/language-core/lib/linkedCodeMap.ts
- packages/language-core/lib/types.ts
- packages/language-server/lib/register/registerEditorFeatures.ts
- packages/language-server/protocol.ts
- packages/language-service/lib/features/provideCallHierarchyItems.ts
- packages/language-service/lib/features/provideCompletionItems.ts
- packages/language-service/lib/features/provideDefinition.ts
- packages/language-service/lib/features/provideDiagnostics.ts
- packages/language-service/lib/features/provideDocumentFormattingEdits.ts
- packages/language-service/lib/features/provideFileReferences.ts
- packages/language-service/lib/features/provideReferences.ts
- packages/language-service/lib/features/provideWorkspaceSymbols.ts
- packages/language-service/lib/features/resolveCompletionItem.ts
- packages/language-service/lib/languageService.ts
- packages/language-service/lib/types.ts
- packages/language-service/lib/utils/common.ts
- packages/language-service/lib/utils/featureWorkers.ts
- packages/language-service/lib/utils/transform.ts
- packages/source-map/lib/buildMappings.ts
- packages/source-map/lib/sourceMap.ts
- packages/test-utils/index.ts
- packages/typescript/lib/node/transform.ts
- packages/typescript/lib/node/utils.ts
- packages/typescript/lib/protocol/createProject.ts
https://github.com/volarjs/volar.js/commit/c4b297b2426ec8b032eec16c5396263bc03e2163 removed multi-source support, but to support Angular use cases, this PR re-implements it.
- `getAssociatedScript` needs to be called to explicitly register dependencies on additional sources.
- Mappings with additional source scripts should be added to `associatedScriptMappings` instead of using the `Mapping#source` field.
- The `Mapping#source` field has beed removed.
Example:
```ts
export const angularLanguagePlugin: LanguagePlugin<string> = {
createVirtualCode(fileName, languageId, snapshot, { getAssociatedScript }) {
if (fileName.endsWith('app.component.ts')) {
// Register dependencies
const templateScript = getAssociatedScript('.../template.html');
if (templateScript) {
return {
mappings: [
// …
```
> feat(language-core): reimplement multi-source mapping

- packages/language-server/lib/project/typescriptProjectLs.ts
- packages/language-server/lib/server.ts
- Every time the file is reopened, because the SnapshotDocument instance is brand new, even if the file content hasn't changed, createVirtualCode will be rerun due to the new snapshot instance. This is resolved by using WeakRef to cache the SnapshotDocument.
- When the file watcher is not enabled (LanguageServer#watchFiles not called), even if the file has been explicitly saved, the FS API always returns the cached result from the first request. This issue is mitigated by updating the cache in onDidSave.
- For TS projects, the snapshot of the document during synchronization is different from the snapshot created from readFile, which causes createVirtualCode to be rerun when closing/opening the file due to switching between the document snapshot and the FS snapshot. This issue is resolved …
> perf(language-server): improve snapshot reusability

- packages/vscode/lib/features/tsVersion.ts
Closes https://github.com/volarjs/volar.js/issues/122
Moves the code away from the assumption that there's always a valid TypeScript distribution available under the `${appRoot}/extensions/node_modules/typescript/lib` path. While I add this change specifically for Theia, there are other (improbable) cases in which the VS Code builtin TypeScript distribution might be malformed or simply unavailable.
I believe this change is breaking as `getTsdk` is exported from the main index and can now also return `undefined` in addition to the original object type.
Note that I'm not too familiar with the project and haven't found any instructions on testing the changes. If something doesn't work as expected, please let me know how I can test my changes before I request another review :)
> fix(vscode): show error on missing TypeScript lib

- packages/monaco/lib/provider.ts
- packages/monaco/package.json
- pnpm-lock.yaml
LSP represents an ancestry of selection ranges using the `parent` property. Monaco editor represents this using an array of selection ranges. This is why one LSP selection range represents an array of Monaco editor selection ranges. It’s not needed to call `getSelectionRanges` multiple times.
> Fix Monaco selection ranges conversion

- packages/language-server/lib/register/registerLanguageFeatures.ts
- packages/language-server/lib/server.ts
- packages/language-service/lib/features/provideDiagnostics.ts
- packages/language-service/lib/features/provideWorkspaceDiagnostics.ts
- packages/language-service/lib/languageService.ts
- packages/language-service/lib/types.ts
- tsslint.config.ts
Close #43, implement `connection.languages.diagnostics.onWorkspace` of language server.
```ts
const plugin: LanguageServicePlugin = {
capabilities: {
diagnosticProvider: {
workspaceDiagnostics: true,
},
},
create(context): LanguageServicePluginInstance<Provide> {
return {
provideWorkspaceDiagnostics() {
return [{
uri: 'file://a.css',
items: [{
severity: 2,
source: 'html1',
message: 'Only one style tag is allowed.',
// ...
}]
}];
}
};
},
}
```
> feat(language-server): add support for Workspace Diagnostics

- packages/language-service/lib/documents.ts
- packages/language-service/lib/features/provideDocumentFormattingEdits.ts
- packages/language-service/lib/features/provideInlayHints.ts
- packages/language-service/lib/features/provideSelectionRanges.ts
- packages/language-service/lib/utils/transform.ts
- packages/source-map/lib/sourceMap.ts
- packages/source-map/tests/sourceMap.spec.ts
- packages/typescript/lib/node/decorateLanguageService.ts
- packages/typescript/lib/node/transform.ts
Add range mapping APIs (`getSourceStartEnd`, `getGeneratedStartEnd`), which will only try to map start, end positions from the same mapping item.
This is the range mapping behavior that was originally `@volar/language-service`, and is now moved into the `@volar/source-map` core so that it is also valid in the TS plugin.
> refactor(source-map): improve range mapping accuracy

- packages/eslint/index.ts
- packages/language-core/index.ts
- packages/language-core/lib/linkedCodeMap.ts
- packages/language-core/lib/types.ts
- packages/language-service/lib/features/provideAutoInsertSnippet.ts
- packages/language-service/lib/features/provideDocumentFormattingEdits.ts
- packages/language-service/lib/utils/common.ts
- packages/language-service/lib/utils/featureWorkers.ts
- packages/language-service/tests/findOverlapCodeRange.spec.ts
- packages/source-map/lib/sourceMap.ts
- packages/source-map/tests/sourceMap.spec.ts
- packages/test-utils/index.ts
- packages/typescript/lib/node/transform.ts
Closes #203
Define the factory function of the source map through `Language.mapperFactory`, which allows the insertion of customized mapping logic.
Individual frameworks may require somewhat special mapping processing logic. For example, WebStorm-Angular requires special processing for overlapping mapping ranges. These processing may not be common to all frameworks, so it is best to make the mapping behavior itself customizable.
After creating the Language instance, set `mapperFactory` property to override the default SourceMap factory function.
```ts
createLanguageServicePlugin((ts, info) => ({
languagePlugins: [/* ... */],
setup(language) {
language.mapperFactory = mappings => new MySourceMap(mappings);
},
});
```
> refactor(language-core): pluginized source map factory function

- packages/language-core/index.ts
fix https://github.com/slidevjs/slidev/issues/1695.
#207 removed the re-exporting of `SourceMap` (https://github.com/volarjs/volar.js/pull/207/files#diff-9b91681a6cad2a7185ae1fa36e153880167c7081a2a664a52c279e3c7f89a52eL1), which should be a breaking change. However, because #207 has been published in a patch version, users installing the downstream packages like `twoslash-vue` and `slidev` will install the new version without being notified. This caused errors, which can only be fixed by overriding the dependencies manually.
This PR re-adds the re-exporting of `SourceMap`. I don't know whether it's good to re-export it, but I think it should be re-added until the next major (or at least minor) version.
> fix(language-core): should re-export `SourceMap`

- packages/language-server/lib/register/registerLanguageFeatures.ts
- packages/language-server/lib/server.ts
- packages/language-server/lib/types.ts
- packages/language-service/lib/types.ts
- packages/vscode/lib/features/autoInsertion.ts
Language features handlers should be registered with respect to language server capabilities. This can avoid unnecessary registration and go some way to solving the problem of hidden side effects discovered by @Andarist.
Additionally, the refactoring mentioned at https://github.com/mdx-js/mdx-analyzer/pull/446#discussion_r1632408332 was also implemented.
> refactor(language-server): respect server capabilities when register language features handlers

- packages/language-server/lib/register/registerLanguageFeatures.ts
- packages/language-server/lib/server.ts
- packages/language-service/lib/features/provideWorkspaceSymbols.ts
- packages/language-service/lib/features/resolveWorkspaceSymbol.ts
- packages/language-service/lib/languageService.ts
- packages/language-service/lib/types.ts
Implemented `connection.onWorkspaceSymbolResolve`. (Currently no language service plugin needs to use it)
> feat(language-service): add support for workspace symbol resolve

- packages/language-server/lib/register/registerLanguageFeatures.ts
- packages/language-server/lib/server.ts
- packages/language-service/lib/languageService.ts
- packages/language-service/lib/types.ts
Closes #120.
Now the language service plugin can directly handle language server executeCommand requests.
> feat(language-service): add support for executeCommand handler

- packages/language-core/index.ts
- packages/language-core/lib/types.ts
- packages/typescript/index.ts
- packages/typescript/lib/node/transform.ts
- packages/typescript/lib/node/utils.ts
- packages/typescript/lib/protocol/createProject.ts
The `Language` and `LanguagePlugin` interface definitions in `@vue/language-core` are no longer coupled with TypeScript. Instead, options specific to TypeScript projects are defined in `@volar/typescript` through TS declaration merging.
> refactor(language-core): decoupled from TypeScript project context

- packages/kit/lib/createChecker.ts
- packages/kit/lib/createFormatter.ts
- packages/kit/lib/utils.ts
- packages/language-server/lib/project/simpleProject.ts
- packages/language-server/lib/project/typescriptProjectLs.ts
- packages/language-server/lib/register/registerEditorFeatures.ts
- packages/language-service/lib/languageService.ts
- packages/language-service/lib/types.ts
- packages/monaco/worker.ts
- packages/typescript/index.ts
- packages/typescript/lib/protocol/createProject.ts
`Language.typescript` is used to pass TS project context to `volar-service-typescript`. Since `Language.typescript` is specific to LSP context, it should be pass through language service instead of `Language` interface.
> refactor(language-service): move project context from `Language` to language service option

- packages/monaco/lib/ata.ts
The `activateAutomaticTypeAcquisition` function has been removed, `createJsDelivrNpmFileSystem` should now be used instead in v2.4.
```ts
const env: LanguageServiceEnvironment = {
workspaceFolders: [URI.file('/')],
locale,
fs: createJsDelivrNpmFileSystem(
uri => {
if (uri.toString().startsWith('file:///node_modules/')) {
return uri.path.substring('/node_modules/'.length)
}
},
pkgName => pkgName
)
};
```
> refactor(monaco): replace activateAutomaticTypeAcquisition

- packages/jsdelivr/LICENSE
- packages/jsdelivr/index.ts
- packages/jsdelivr/lib/npm.ts
- packages/jsdelivr/package.json
- packages/jsdelivr/tsconfig.json
- packages/monaco/README.md
- packages/monaco/worker.ts
- pnpm-lock.yaml
- tsconfig.json
In #126 `@volar/cdn` was merged into `@volar/monaco`, which was the wrong refactoring because ATA is not specific to Monaco and Web IDE also relies on it.
This PR add `@volar/jsdelivr` module to reimplement `@volar/cdn`.
> refactor(monaco): move ATA to `@volar/jsdelivr`

- packages/language-server/lib/register/registerLanguageFeatures.ts
- packages/language-server/lib/server.ts
- packages/language-service/lib/features/provideDiagnostics.ts
- packages/language-service/lib/features/provideDocumentSemanticTokens.ts
- packages/monaco/lib/editor.ts
- packages/monaco/lib/provider.ts
- packages/monaco/lib/requestId.ts
- packages/monaco/worker.ts
Now need to pass in `requestId` when calling `WorkerLanguageService` APIs, and it can notify `WorkerLanguageService` to cancel the request by calling `cancelRequest(requestId)`. These API changes are internal and developers shouldn't care about it.
> feat(monaco): implement CancellationToken for workers

- packages/typescript/lib/quickstart/runTsc.ts
This PR will solve the `error TS5055: Cannot write file 'xxx/yyy.vue.d.ts' because it would overwrite input file.` error, and the problem that `--clean` cannot clean the `.vue.d.ts` file.
- extra extensions need to be added to the first group of `supportedTSExtensions`, which will make tsc think that `.vue` and `.vue.d.ts` are associated file types, thus solving the problem that `.vue` and `.vue.d.ts` are considered multiple source file problem.
- Extra extensions need to be located in front of `.d.ts.` tsc depends on the order to determine the priority of `.vue` and `.vue.d.ts`.
- Patch `changeExtension` to resolve tsc not knowing it should convert `xxx.vue` to `xxx.vue.d.ts` instead of `xxx.d.ts`.
> fix(typescript): improve accuracy of `runTsc` extensions parameter behavior

- packages/monaco/lib/provider.ts
- packages/monaco/package.json
- pnpm-lock.yaml
The most important change for Volar, is that the default diagnostic severity is now error.
See https://github.com/remcohaszing/monaco-languageserver-types/releases/tag/v0.4.0
> chore(monaco): update to monaco-languageserver-types 0.4

- packages/language-server/lib/project/typescriptProject.ts
- packages/language-server/lib/register/registerLanguageFeatures.ts
- packages/language-server/lib/server.ts
- packages/language-service/lib/features/provideDiagnostics.ts
- packages/language-service/lib/types.ts
- Removed the `provideSemanticDiagnostics` hook, LanguageServicePlugin should prompt that `provideDiagnostics` needs to be recalculated when other files change through `capabilities.diagnosticProvider.interFileDependencies = true`.
- The `pullModelDiagnostics` option has been removed. Volar will maintain its own logic to determine whether to enable pull model: when the language client supports pull diagnostics and no LanguageServicePlugin enables `interFileDependencies`, pull diagnostics will be used. Otherwise use push diagnostics. The reason is that according to the summary in https://github.com/microsoft/vscode-languageserver-node/issues/848#issuecomment-2189521060, the pull model is currently not reliable enough.
> refactor(langauge-server): Improve LSP diagnostic integration

- packages/kit/lib/createChecker.ts
- packages/language-core/index.ts
- packages/language-core/lib/types.ts
- packages/language-server/lib/project/typescriptProjectLs.ts
- packages/monaco/worker.ts
- packages/typescript/lib/node/proxyCreateProgram.ts
- packages/typescript/lib/protocol/createProject.ts
Resolves https://github.com/withastro/language-tools/issues/920
> feat(kit): add support for checking project references files

- packages/language-service/lib/features/provideCodeActions.ts
- packages/language-service/lib/features/provideCodeLenses.ts
- packages/language-service/lib/features/provideCompletionItems.ts
- packages/language-service/lib/features/provideDocumentLinks.ts
- packages/language-service/lib/features/provideInlayHints.ts
- packages/language-service/lib/features/provideWorkspaceSymbols.ts
Some plugins like `volar-service-css`, `volar-service-html` do not support completion item resolve, so there is no need to set data for completion item, which can reduce LSP traffic.
> fix(language-service): don't send data to client if LanguageServicePlugin do not support resolve

- packages/language-server/lib/project/typescriptProjectLs.ts
- packages/language-service/lib/features/resolveCodeAction.ts
- packages/language-service/lib/features/resolveCodeLens.ts
- packages/language-service/lib/features/resolveCompletionItem.ts
- packages/language-service/lib/features/resolveDocumentLink.ts
- packages/language-service/lib/features/resolveInlayHint.ts
- packages/language-service/lib/features/resolveWorkspaceSymbol.ts
- packages/test-utils/README.md
- packages/test-utils/index.ts
- packages/typescript/lib/protocol/createSys.ts
This is a change made for `test-utils`. The test code can make the TS language server think that a certain file exists through `openInMemoryDocument`, even if the file does not exist in FS.
Example: https://github.com/vuejs/language-tools/blob/13924d1d2fb8a6f11c267dd4612c366502c1cbc5/packages/language-server/tests/inlayHints.spec.ts#L232
> feat(language-server): support files that do not exist in FS but are open in the editor for TS project

- packages/language-server/browser.ts
- packages/language-server/lib/features/languageFeatures.ts
- packages/language-server/lib/server.ts
- packages/language-server/lib/types.ts
- packages/language-server/node.ts
As mentioned in the [comment](https://github.com/vuejs/language-tools/issues/4593#issuecomment-2304245223), it 。seems more reasonable to replace `setTimeout` with `setImmediate`.
1. `volar` uses `vscode-languageserver-node`, [which uses setImmediate to process messages](https://github.com/microsoft/vscode-languageserver-node/blob/main/jsonrpc/src/common/connection.ts#L723).
2. [the built-in HTML plugin of vscode also uses setImmediate to wrap the runner].(https://github.com/microsoft/vscode/blob/main/extensions/html-language-features/server/src/utils/runner.ts#L21).
3. this ensures the order of message processing.
🤔
> refactor: replace setTimeout with setImmediate

- packages/typescript/lib/node/proxyLanguageService.ts
I've started working on support of inlay hints for Angular templates and I've noticed some issues.
> fix(typescript): fix inlay hints mapping for large chunks of source code mapped verbatim to generated code.

- packages/language-server/lib/utils/snapshotDocument.ts
- packages/language-server/tests/snapshotDocument.spec.ts
fixes https://github.com/vuejs/language-tools/issues/4909
`calculateChangeRange` was incorrectly calculating combined change if the document update contained multiple changes. It calculated offset for each change using the original state of the document as a base while the offsets for the next change need to be calculated based on a document state with previous change applied.
I'm guessing that vscode coalesced changes so generally there was just a single one and the issue was never apparent there but with other editors there is no such guarantee.
To fix I've dropped the incorrect code and instead switched to converting changes to `ts.TextChangeRange`s and using existing `combineChangeRanges` utility function that seems to be doing the right thing.
Calculating incorrect range for the …
> fix(language-server): correctly calculate coalesced document change

- packages/typescript/lib/protocol/createProject.ts
In TS 5.6, this method is called on the host to try to get the cache, unfortunately since we were not setting it, on every single keystroke TS would reload every single package json in the project, causing completions to take 200+ms to load every time.
TS 5.5:
Before (TS 5.6):
After (TS 5.6):
I'll note that this is still slower than TS 5.5, there's probably more things that should be cached that aren't, not sure.
> fix: set module resolution cache

- packages/typescript/lib/node/proxyLanguageService.ts
- packages/typescript/lib/node/transform.ts
Fixes https://github.com/vuejs/language-tools/issues/4811, closes https://github.com/vuejs/language-tools/pull/4906
In the past we mapped results in discrete mapping regions for all TS features, however for content-sensitive features (such as autocomplete/formatting), results should only be returned in continuous mapping regions.
Affected features:
- getFormattingEditsForDocument
- getFormattingEditsForRange
- getFormattingEditsAfterKeystroke
- getEditsForFileRename
- getLinkedEditingRangeAtPosition
- organizeImports
- getDocumentHighlights
- getEditsForRefactor
- getCombinedCodeFix
- getRenameInfo
- getCodeFixesAtPosition
- getEncodedSemanticClassifications
- findRenameLocations
- getCompletionsAtPosition
- getCompletionEntryDetails
cc @piotrtomiak, @KazariEX
> fix(typescript): content-sensitive features are only allowed to return results in contiguous mapped ranges

- packages/typescript/lib/node/proxyLanguageService.ts
Passing along this argument is required since you proxy `includeInteractiveActions` in `getApplicableRefactors`. Without this, VS Code’s “Move to File” refactor fails for all TypeScript users who have the extension installed:
https://github.com/user-attachments/assets/2e169eff-b220-4ae5-8d4e-1017b0d9eaa7
> fix(typescript): Fix interactive refactors

- packages/language-core/index.ts
- packages/language-core/lib/types.ts
- packages/typescript/lib/node/decorateLanguageServiceHost.ts
- packages/typescript/lib/quickstart/createAsyncLanguageServicePlugin.ts
- packages/typescript/lib/quickstart/createLanguageServicePlugin.ts
Angular plugin is transpiling the TS files. Within `getScriptSnapshot` there is a code which associated scrip info with a project. Without this call, scripts are orphaned and wrong config is used during highlighting. Not sure if this fix should apply to all types of files though
> fix(typescript): fix issue with transpiled TypeScript files not being registered with a project at all

- packages/monaco/README.md
This pull request submits several changes to the `@volar/monaco` documentation to match the current status of the API. It is a follow up of [this comment](https://github.com/volarjs/volar.js/discussions/151#discussioncomment-11608669) from @johnsoncodehk.
1. The module `@volar/monaco/worker` doesn't export a `ServiceEnvironment` type anymore. The `createSimpleWorkerLanguageService` and `createTypeScriptWorkerLanguageService` utility functions [use the `LanguageServiceEnvironment` type from `@volar/language-service`](https://github.com/volarjs/volar.js/blob/15fa6bf14906a9289e47c2335c7f8caa8263f44f/packages/monaco/worker.ts#L30) as the type of the `env` parameter.
2. The `LanguageServiceEnvironment` type [admits a `workspaceFolders` property instead of a `workspaceFolder` …
> docs(monaco): update documentation to match the current API status

- packages/language-core/index.ts
- packages/typescript/lib/quickstart/languageServicePluginCommon.ts
In Glint, when the association script (.hbs) is updated and the target script (.ts) is not, the association script's diagnostics don't refresh correctly because the target script's getScriptVersion value hasn't changed.
We can't proxy getScriptVersion to deal with this, that would cause serious performance issues with the tsserver some how, so we send a change event to the tsserver session to force the target script to be considered new.
/cc @piotrtomiak, @machty
> fix(typescript): focus update target file version on association dirty

- packages/typescript/lib/node/proxyLanguageService.ts
- packages/typescript/lib/node/transform.ts
fix issue when mapping ranges are exactly the same as ranges passed to getFixesAtPosition and getFormattingEditsForRange
> fix(typescript): fix issue when mapping ranges are exactly the same as ranges passed to getFixesAtPosition and getFormattingEditsForRange

- packages/typescript/lib/resolveModuleName.ts
fix https://github.com/vuejs/language-tools/issues/5366
> fix(typescript): skip source file search when `.d.${ext}.ts` file exists

- packages/typescript/lib/quickstart/runTsc.ts
Hello, I tried to find a way to use `vue-tsc` programmatically to pass it into tools like `webpack/rspack-ts-checker`, but it is currently designed to simply invoke only `tsc` cli.
This PR in combination with a [same change on `vue-tsc` side](https://github.com/vuejs/language-tools/pull/5517) will allow to make use of not just `lib/tsc`, but also `lib/typescript` and pass it to any tool that expects the typescript API as simply as
```js
// vue-typescript.js
module.exports = require('vue-tsc').runTsc(require.resolve('typescript'))
```
```js
...
someCheckerPlugin({
typescript: require.resolve('./vue-typescript')
})
...
```
> refactor(typescript): return patched typescript package
